/* eslint-disable @typescript-eslint/no-unused-expressions */
import { Buffer } from 'safe-buffer';
import { expect } from 'chai';
import { test, assertThrowsAsync } from '../util';
import { fixtures, type ValidFixture } from './fixtures';

import crypto from 'react-native-quick-crypto';
import type { BinaryLike } from 'react-native-quick-crypto';

type TestFixture = [string, string, number, number, string];

// Copied from https://github.com/crypto-browserify/pbkdf2/blob/master/test/index.js
// SHA-1 vectors generated by Node.js
// SHA-256/SHA-512 test vectors from:
// https://stackoverflow.com/questions/5130513/pbkdf2-hmac-sha2-test-vectors
// https://stackoverflow.com/questions/15593184/pbkdf2-hmac-sha-512-test-vectors

const SUITE = 'pbkdf2';

// RFC 6070 tests from Node.js
//
// The async callbacks must be awaited. Pre-fix, the callback assertions ran
// fire-and-forget after the test had already resolved — so a wrong digest
// would not fail the test. Wrap each call in a Promise that resolves on the
// callback and rejects when an assertion throws.
{
  const testFn = (
    pass: string,
    salt: string,
    iterations: number,
    hash: string,
    length: number,
    expected: string,
  ) => {
    return new Promise<void>((resolve, reject) => {
      crypto.pbkdf2(
        pass,
        salt,
        iterations,
        length,
        hash,
        function (err, result) {
          try {
            expect(err).to.be.null;
            expect(result).not.to.be.null;
            expect(result?.toString('hex')).to.equal(expected);
            resolve();
          } catch (e) {
            reject(e);
          }
        },
      );
    });
  };

  const kTests: TestFixture[] = [
    ['password', 'salt', 1, 20, '120fb6cffcf8b32c43e7225256c4f837a86548c9'],
    ['password', 'salt', 2, 20, 'ae4d0c95af6b46d32d0adff928f06dd02a303f8e'],
    ['password', 'salt', 4096, 20, 'c5e478d59288c841aa530db6845c4c8d962893a0'],
    [
      'passwordPASSWORDpassword',
      'saltSALTsaltSALTsaltSALTsaltSALTsalt',
      4096,
      25,
      '348c89dbcbd32b2f32d814b8116e84cf2b17347ebc1800181c',
    ],
    ['pass\0word', 'sa\0lt', 4096, 16, '89b69d0516f829893c696226650a8687'],
    [
      'password',
      'salt',
      32,
      32,
      '64c486c55d30d4c5a079b8823b7d7cb37ff0556f537da8410233bcec330ed956',
    ],
  ];

  kTests.forEach(([pass, salt, iterations, length, expected]) => {
    const hash = 'sha256';
    test(
      SUITE,
      `RFC 6070 - ${pass} ${salt} ${iterations} ${hash} ${length}`,
      () => testFn(pass, salt, iterations, hash, length, expected),
    );
  });
}

test(SUITE, 'handles buffers', () => {
  const resultSync = crypto.pbkdf2Sync('password', 'salt', 1, 32, 'sha1');
  expect(resultSync?.toString('hex')).to.equal(
    '0c60c80f961f0e71f3a9b524af6012062fe037a6e0f0eb94fe8fc46bdc637164',
  );

  return new Promise<void>((resolve, reject) => {
    crypto.pbkdf2(
      Buffer.from('password'),
      Buffer.from('salt'),
      1,
      32,
      'sha1',
      function (err, result) {
        try {
          expect(err).to.be.null;
          expect(result?.toString('hex')).to.equal(
            '0c60c80f961f0e71f3a9b524af6012062fe037a6e0f0eb94fe8fc46bdc637164',
          );
          resolve();
        } catch (e) {
          reject(e);
        }
      },
    );
  });
});

test(SUITE, 'should throw if no callback is provided', function () {
  expect(() => {
    // @ts-expect-error - testing no callback
    crypto.pbkdf2('password', 'salt', 1, 32, 'sha1');
  }).to.throw(/No callback provided to pbkdf2/);
});

test(
  SUITE,
  'should throw if the password is not a string or an ArrayBuffer',
  function () {
    expect(() => {
      // @ts-expect-error - testing bad password
      crypto.pbkdf2(['a'], 'salt', 1, 32, 'sha1');
    }).to.throw(/No callback provided to pbkdf2/);
  },
);

test(
  SUITE,
  ' should throw if the salt is not a string or an ArrayBuffer',
  function () {
    expect(() => {
      // @ts-expect-error - testing bad salt
      crypto.pbkdf2('a', ['salt'], 1, 32, 'sha1');
    }).to.throw(/No callback provided to pbkdf2/);
  },
);

const algos = ['sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'ripemd160'];
algos.forEach(function (algorithm) {
  fixtures.valid.forEach(function (f: ValidFixture) {
    let key: BinaryLike, keyType: string, salt: BinaryLike, saltType: string;
    if (f.keyUint8Array) {
      key = new Uint8Array(f.keyUint8Array);
      keyType = 'Uint8Array';
    } else if (f.keyInt32Array) {
      key = new Int32Array(f.keyInt32Array);
      keyType = 'Int32Array';
    } else if (f.keyFloat64Array) {
      key = new Float64Array(f.keyFloat64Array);
      keyType = 'Float64Array';
    } else if (f.keyHex) {
      key = Buffer.from(f.keyHex, 'hex');
      keyType = 'hex';
    } else {
      key = f.key as BinaryLike;
      keyType = 'string';
    }
    if (f.saltUint8Array) {
      salt = new Uint8Array(f.saltUint8Array);
      saltType = 'Uint8Array';
    } else if (f.saltInt32Array) {
      salt = new Int32Array(f.saltInt32Array);
      saltType = 'Int32Array';
    } else if (f.saltFloat64Array) {
      salt = new Float64Array(f.saltFloat64Array);
      saltType = 'Float64Array';
    } else if (f.saltHex) {
      salt = Buffer.from(f.saltHex, 'hex');
      saltType = 'hex';
    } else {
      salt = f.salt as BinaryLike;
      saltType = 'string';
    }
    const expected = f.results[algorithm];
    const description =
      algorithm +
      ' encodes "' +
      key +
      '" (' +
      keyType +
      ') with salt "' +
      salt +
      '" (' +
      saltType +
      ') with ' +
      algorithm +
      ' to ' +
      expected;

    test(SUITE, ' async w/ ' + description, () => {
      return new Promise<void>((resolve, reject) => {
        crypto.pbkdf2(
          key,
          salt,
          f.iterations,
          f.dkLen,
          algorithm,
          function (err, result) {
            try {
              expect(err).to.be.null;
              expect(result).not.to.be.null;
              expect(result?.toString('hex')).to.equal(expected);
              resolve();
            } catch (e) {
              reject(e);
            }
          },
        );
      });
    });

    test(SUITE, 'sync w/ ' + description, function () {
      const result = crypto.pbkdf2Sync(
        key,
        salt,
        f.iterations,
        f.dkLen,
        algorithm,
      );
      expect(result?.toString('hex')).to.equal(expected);
    });
  });

  fixtures.invalid.forEach(function (f) {
    test(
      SUITE,
      `invalid: ${algorithm} throws "${f.exception}" for iterations=${f.iterations} keylen=${f.dkLen}`,
      () => {
        expect(() => {
          crypto.pbkdf2Sync(
            f.key as string,
            f.salt as string,
            f.iterations as number,
            f.dkLen as number,
            algorithm,
          );
        }).to.throw(f.exception);
      },
    );
  });
});

// --- Phase 4.5: fire-and-forget async assertion regression ---
//
// Mirrors the random suite's regression check. A wrong expected digest
// inside the callback must now reject the returned Promise — pre-fix this
// would silently pass.
test(SUITE, 'fire-and-forget regression: failing assert rejects the test', () =>
  assertThrowsAsync(
    () =>
      new Promise<void>((resolve, reject) => {
        crypto.pbkdf2('password', 'salt', 1, 20, 'sha1', (err, result) => {
          try {
            expect(err).to.be.null;
            expect(result?.toString('hex')).to.equal('deadbeef'); // wrong
            resolve();
          } catch (e) {
            reject(e);
          }
        });
      }),
    'expected',
  ),
);
