name: Build Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'example/android/**'
      - 'yarn.lock'
      - 'example/yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'example/android/**'
      - 'yarn.lock'
      - 'example/yarn.lock'

jobs:
  build_android_example:
    name: Build Android Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clear up some disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.22

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Bootstrap JS
        run: |
          bun install

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle Build for android/
        run: cd packages/react-native-quick-crypto/android && ./gradlew assembleDebug && cd ../..

      - name: Run Gradle Build for example/android/
        run: cd example/android && ./gradlew assembleDebug --build-cache && cd ../..
