name: Create Github Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release_github:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
        run: |
          gh release create $tag_name \
            --repo="$GITHUB_REPOSITORY" \
            --title="Release ${tag_name#v}" \
            --generate-notes
